name: Continuous Delivery
on:
  push:
    branches:
      - main
jobs:
  Deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: CD
        uses: actions/upload-artifact@v7
        with:
          name: projeto.zip
          path: |
            **.py
            README.md

  Deployment:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
    - uses: actions/download-artifact@v8
      with:
        name: projeto.zip
    - name: Display structure of downloaded files
      run: ls -R